### ISSUE TITLE
FreeNAS (FreeBSD variant) doesn't display any content with smbios.system.uuid property

### ISSUE THREAD

**Issue by xor-gate** [denisbrodbeck/machineid#1]
I tried your commands on a FreeBSD -> [FreeNAS](https://en.wikipedia.org/wiki/FreeNAS) variant system and the machineid is empty. Probably we should check if empty for a file at `/etc/hostid`. See below:

```
root@shulgin:~ # kenv -q smbios.system.uuid
root@shulgin:~ # /etc/rc.d/hostid start
Setting hostuuid: e1e7d8e1-8432-11e7-b267-0cc47a40cb81
root@shulgin:~ # cat /etc/hostid
e1e7d8e1-8432-11e7-b267-0cc47a40cb81
```

**Comment by denisbrodbeck** [comment]
Hey @xor-gate, you're right.
Fired up a fresh FreeNAS 11 VM and verified the issue.

Changed [doc](README.md) and [code](https://github.com/denisbrodbeck/machineid/commit/b10ec6113b9b6c64a81910e8aacd5e53ab4c36ef) to:

1. read `/etc/hostid`
2. call `kenv -q smbios.system.uuid`, if previous step fails

Thanks for reporting this issue :+1:

**Comment by xor-gate** [comment]
Great! If you are interested I have some of your work derived and added to my package. But this uses a different approach (sysdetect interface, eg local or SSH). See https://github.com/xor-gate/sysdetect/blob/master/machineid.go
