### ISSUE TITLE
Why different machines has same machineId?

### ISSUE THREAD

**Issue by heramerom** [denisbrodbeck/machineid#6]
I have two ECS in Aliyun cloud. The machines has the same machineId. but I want a unique id for each machine. How can I do?

**Comment by heramerom** [comment]
I think the Vm merchant is disk clone system. not install from a ISO.

**Comment by denisbrodbeck** [comment]
If it's a recent Linux based system, you could try to regenerate the id once when provisioning the vm's initially.

The tool you need is `dbus-uuidgen --ensure` (see [man-page](https://dbus.freedesktop.org/doc/dbus-uuidgen.1.html)). You also might want to checkout [this SE answer](https://unix.stackexchange.com/a/403054) with more details, which files exactly to regenerate/remove.
